### ISSUE TITLE
Flask App is Showing 404 Not Found

### ISSUE THREAD

**Issue by Aaditya188** [mamonraab/fire-detection-in-video-with-pytroch#4]
Can u pls tell me how to run the files in a browser. I am not able to decode it. Whenever I am running the code it is showing 404 Not Found. I have installed all the dependencies

Thanks for help in Advance

**Comment by mamonraab** [comment]
once you run the https://github.com/mamonraab/violance-detection-in-video-with-pytroch/blob/main/flaskapp/web-fight.py   , the app will listen on port 3091  , and expect you to send a video file at this endpoint (/api/fight/)   >> the client.py https://github.com/mamonraab/violance-detection-in-video-with-pytroch/blob/main/flaskapp/client.py   is an example of sending video file to the endpoint
